In [1]:
from sqlalchemy import create_engine
import numpy as np
import datetime

import trueskill
from collections import defaultdict

In [331]:
env = trueskill.TrueSkill(draw_probability=0.25)

teams = defaultdict(env.create_rating, sigma = 8.3333)

date_old = data[0][3]
dates = defaultdict(lambda:date_old)
budget = 100
bets = 0
res = ['H', 'D', 'A']
onehot = [[1,0,0],[0,1,0],[0,0,1]]
oh = {k:v for k,v in zip(res,onehot)}
conf_matrix = [[0,0,0],[0,0,0],[0,0,0]]
pred = [0,0,0]
stuff = []
stuff2 = []

for m in data:
    t1 = int(m[1]/1000000)
    t2 = int(m[2]/1000000)
    
    r1 = teams[t1]
    r2 = teams[t2]
    
    date_new = m[3]
    date_old = dates[t1]
    
    if datetime.timedelta(60) < abs(date_new-date_old):
        r1 = env.create_rating(r1.mu, 2.8*r1.sigma)
    date_old = dates[t2]
    if datetime.timedelta(60) < abs(date_new-date_old):    
        r2 = env.create_rating(r2.mu, 2.8*r2.sigma)
    
    probs = win_probability(r1,r2)
    
    if r1.sigma+r2.sigma < 3:
        odds = np.subtract(m[-3:], probs**(-1))
        if max(odds) > .25:
            r = np.argmax(odds)
            budget -= 1
            bets += 1
            if m[0] == res[r]:
                budget += m[int(-3+r)]
    
    if r1.pi < 0.0000001 or r2.pi < 0.0000001:
        continue
        
    if m[0] == 'H':
        r1,r2 = env.rate_1vs1(r1,r2)
    elif m[0] == 'D':
        r1,r2 = env.rate_1vs1(r1,r2,drawn=True)
    elif m[0] =='A':
        r2,r1 = env.rate_1vs1(r2,r1)
    else:
        print('wrong result: '+m[0])
    
    ix = np.argmax(probs)
    stuff.append(np.subtract(probs,oh[m[0]])**2)
    conf_matrix[ix] = np.add(conf_matrix[ix], oh[m[0]])
    pred = np.add(pred, np.multiply(oh[m[0]], onehot[ix]))
    
    teams[t1] = r1
    teams[t2] = r2
    dates[t1] = date_new
    dates[t2] = date_new
    
print('%.2f $ from %s bets' % (budget,bets))
print(np.mean(stuff, axis = 0))
print('correct: ', pred, ', insgesamt %d/%d (%.3f)' % (sum(pred), len(stuff), sum(pred)/len(stuff)))
for l in conf_matrix:
    print(' %5d | %5d | %5d ' % (l[0], l[1], l[2]))

28.75 $ from 194 bets
[ 0.23885463  0.18399141  0.19984396]
correct:  [931   0 266] , insgesamt 1197/2387 (0.501)
   931 |   451 |   456 
     0 |     0 |     0 
   154 |   129 |   266 


In [300]:
ix

0

In [227]:
print([x**2 for x in [0.47,0.25,0.28]])
print(np.mean(stuff, axis=0))
print(np.mean(stuff2, axis=0))

[0.22089999999999999, 0.0625, 0.07840000000000001]
[ 0.24817273  0.18399141  0.21148756]
[ 0.24844959  0.1826867   0.21060537]


In [28]:
team_names = {x[0]:x[1] for x in c.execute('SELECT sofifaTeamID, name FROM team WHERE ligaID=19')}

In [153]:
ranks = []
for key in teams.keys():
    ranks.append([key,team_names[key], str(teams[key].mu), str(teams[key].sigma)])

ranks = np.array(ranks)
for rank in ranks[np.argsort(ranks[:,2] )][::-1]:
    print(" %6s | %30s | %6s | %5s" % (rank[0],rank[1],rank[2][:6],rank[3][:5]))

     21 |               FC Bayern Munich | 32.015 | 1.145
     22 |              Borussia Dortmund | 28.864 | 1.020
 112172 |                     RB Leipzig | 28.775 | 1.303
  10029 |            TSG 1899 Hoffenheim | 27.148 | 0.987
     31 |                     1. FC Koln | 26.053 | 0.980
     23 |       Borussia Monchengladbach | 26.003 | 1.002
     32 |            Bayer 04 Leverkusen | 25.867 | 1.001
     34 |                  FC Schalke 04 | 25.816 | 0.991
    166 |              Hertha BSC Berlin | 25.517 | 1.017
     38 |               SV Werder Bremen | 25.133 | 1.015
     25 |                    SC Freiburg | 25.131 | 1.006
 100409 |                    FC Augsburg | 24.910 | 0.992
   1824 |            Eintracht Frankfurt | 24.839 | 0.994
    175 |                  VfL Wolfsburg | 24.824 | 1.008
    169 |                1. FSV Mainz 05 | 24.695 | 1.003
     28 |                   Hamburger SV | 24.455 | 1.004
 111239 |               FC Ingolstadt 04 | 23.891 | 1.072
     36 |     

In [326]:
import math
from trueskill.backends import cdf
def win_probability(a, b, env=env): 
    BETA = env.beta
    deltaMu = a.mu - b.mu                   
    sumSigma = a.sigma**2 + b.sigma**2  
    denominator = math.sqrt(2 * (BETA * BETA) + sumSigma)             
    h = .46*cdf(deltaMu / denominator)
#     d = .25*env.quality_1vs1(r1,r2)
    a = .29*(1-h)
#     return np.array([h,d,a]) 
#     return np.array([h,d,a])/np.sum([h,d,a])
    h = h/(h+a)
    a = a/(h+a)
    return np.array([h*0.75, 0.25, a*0.75])
    

In [84]:
for h,a in zip([169,485,32,34,166,10029,21,38,36],[1824,22,31,175,28,23,112172,100409,25]):
    probs = win_probability(teams[h],teams[a])
    print(team_names[h], team_names[a], probs**-1)

1. FSV Mainz 05 Eintracht Frankfurt [ 2.9923666   3.23671554  2.80221011]
Hannover 96 Borussia Dortmund [ 9.33425053  2.67198015  1.92821862]
Bayer 04 Leverkusen 1. FC Koln [ 3.10553165  3.20043628  2.73570459]
FC Schalke 04 VfL Wolfsburg [ 2.51786777  3.43828121  3.20517379]
Hertha BSC Berlin Hamburger SV [ 2.56025531  3.41606994  3.15776277]
TSG 1899 Hoffenheim Borussia Monchengladbach [ 2.37587651  3.52092033  3.38884198]
FC Bayern Munich RB Leipzig [ 2.21539625  3.63308638  3.65810721]
SV Werder Bremen FC Augsburg [ 2.71551295  3.3427319   3.00671451]
VfB Stuttgart SC Freiburg [ 3.7628083   3.04290012  2.46543953]


In [168]:
prediction = [[1,0,0], [1,0,0]]
result = [[1,0,0],[0.33,0.33,.33]]
stuff = []
for p,r in zip(prediction, result):
    stuff.append(np.subtract(p,r)**2)

In [330]:
c = create_engine('mysql+mysqlconnector://root:databaselogin@soccer.colzfodvmhs1.eu-central-1.rds.amazonaws.com/soccerdb')
c.connect()
data = [x for x in c.execute('SELECT FTR, homeID, awayID, spieltag, whh, whD, wha FROM spiel WHERE ligaID=19 ORDER BY spieltag')]


In [296]:
res = ['H', 'D', 'A']
onehot = [[1,0,0],[0,1,0],[0,0,1]]
oh = {k:v for k,v in zip(res,onehot)}
conf_matrix = [[0,0,0],[0,0,0],[0,0,0]]
pred = [0,0,0]
stuff = []
for m in data:
    odds = m[-3:]
    if 0 in odds:
        continue
    probs = np.divide([1/x for x in odds],sum([1/x for x in odds]))
    r = np.argmin(odds)
    pred = np.add(pred,np.multiply(onehot[r], oh[m[0]]))
    conf_matrix[r] = np.add(conf_matrix[r], oh[m[0]])
    stuff.append(np.subtract(probs,oh[m[0]])**2)

print(np.mean(stuff, axis = 0))
print('correct: ', pred, ', insgesamt %d/%d (%.3f)' % (sum(pred), len(stuff), sum(pred)/len(stuff)))
for l in conf_matrix:
    print(' %5d | %5d | %5d ' % (l[0], l[1], l[2]))

[ 0.22235415  0.19120759  0.18688405]
correct:  [11617    17  3613] , insgesamt 15247/30337 (0.503)
 11617 |  5968 |  5197 
     8 |    17 |    11 
  1962 |  1944 |  3613 


In [ ]:
# Hier mal predictor Performance von verschiedenen Quellen. 
# Erste Zeile: durchschnittlicher Quadratischer fehler von Verhersage und Ergebnis
# Zweite Zeile: Richtige Vorhersagen auf basis der groessten Wahrscheinlichkeit
# 3ff: Konfusion matrix, 1. Zeile: Heimsieg vorhergesagt
#                        2. Zeile: Unentschieden vorhergesagt ....

Baseline: Prediction der Wettanbieter:
bet365: 
(prediction-result)** 2: [ 0.222  0.191  0.187]
accuracy: 15295/30337 (0.504)
confusioin matrix: 
 11530 |  5859 |  5076 
     6 |    15 |     6 
  2056 |  2058 |  3750 

bwin:
[ 0.222  0.191  0.187]
accuracy: 15239/30337 (0.503)
confusioin matrix: 
 11573 |  5908 |  5160 
     6 |     8 |     5 
  2006 |  2000 |  3658 

william hill:
[ 0.222  0.191  0.187]
accuracy:  15247/30337 (0.503)
confusioin matrix: 
 11617 |  5968 |  5197 
     8 |    17 |    11 
  1962 |  1944 |  3613 

(Datensatz, wo daten entprechend vorhanden)

vgl: 
Neuronales Netz
[ 0.285, 0.205, 0.207]
accuracy: 729/1519 (0.4799)
confusioin matrix: 
573 | 297 | 287
 29 |  16 |  12 
 90 |  75 |  140

TrueSkill(Teams, mit unentschieden):
[ 0.24500264  0.19609217  0.20387316]
accuracy: 13330/29436 (0.453)
  7751 |  3560 |  3003 
  1046 |   731 |   702 
  4393 |  3402 |  4848 
## Viel mehr Unentschieden(aber ungenau.)

TrueSkill(Teams, unentschieden fest auf 25% (nie vorhersagen)):
[ 0.23989077  0.1931603   0.19762001]
accuracy 14638/30365 (0.482)
 11856 |  6326 |  6051 
     0 |     0 |     0 
  1741 |  1609 |  2782 



In [339]:
c = create_engine('mysql+mysqlconnector://root:databaselogin@soccer.colzfodvmhs1.eu-central-1.rds.amazonaws.com/soccerdb')
c.connect()
data = [x for x in c.execute('SELECT FTR, homeID, awayID, spieltag, homePlayer1, homePlayer2, homePlayer3, homePlayer4,homePlayer5, homePlayer6,homePlayer7, homePlayer8,homePlayer9, homePlayer10,homePlayer11, awayPlayer1, awayPlayer2, awayPlayer3, awayPlayer4, awayPlayer5, awayPlayer6, awayPlayer7, awayPlayer8, awayPlayer9, awayPlayer10, awayPlayer11, whh, whD, wha FROM spiel ORDER BY spieltag')]


In [343]:
def win_probability_team(a, b,env=env2):  
    BETA = env.beta
    deltaMu = sum([x.mu for x in a]) - sum([x.mu for x in b])                   
    sumSigma = sum([x.sigma ** 2 for x in a]) + sum([x.sigma ** 2 for x in b])  
    playerCount = len(a) + len(b)                                               
    denominator = math.sqrt(playerCount * (BETA * BETA) + sumSigma)             
    h = .46*cdf(deltaMu / denominator)
#     d = .25*env.quality(a,b)
    a = .29*(1-h)
#     return np.array([h,d,a]) 
#     return np.array([h,d,a])/np.sum([h,d,a])
    h = h/(h+a)
    a = a/(h+a)
    return np.array([h*0.75, 0.25, a*0.75])
    

In [348]:
env = trueskill.TrueSkill(draw_probability=0.25)
env2 = trueskill.TrueSkill(draw_probability=0.25)



teams = defaultdict(env.create_rating, sigma = 8.3333)
players = defaultdict(env2.create_rating, sigma = 8.3333)

date_old = data[0][3]
dates = defaultdict(lambda:date_old)
budget = 100
bets = 0
res = ['H', 'D', 'A']
onehot = [[1,0,0],[0,1,0],[0,0,1]]
oh = {k:v for k,v in zip(res,onehot)}
conf_matrix = [[0,0,0],[0,0,0],[0,0,0]]
pred = [0,0,0]
stuff = []
stuff2 = []

for m in data:
    t1 = int(m[1]/1000000)
    t2 = int(m[2]/1000000)
    
    r1 = teams[t1]
    r2 = teams[t2]
    
    tr1 = []
    tr2 = []
    for pr in m[4:15]:
        tr1.append(players[int(pr/1000000)])
    for pr in m[15:-3]:
        tr2.append(players[int(pr/1000000)])
    
    date_new = m[3]
    date_old = dates[t1]
    
    if datetime.timedelta(60) < abs(date_new-date_old):
        r1 = env.create_rating(r1.mu, 2.8*r1.sigma)
    date_old = dates[t2]
    if datetime.timedelta(60) < abs(date_new-date_old):    
        r2 = env.create_rating(r2.mu, 2.8*r2.sigma)
    
    probs_team = win_probability(r1,r2,env)
    
    probs_player = win_probability_team(tr1,tr2,env2)
    
    probs = np.mean([probs_team,probs_player], axis = 0)
    
    if r1.pi < 0.0000001 or r2.pi < 0.0000001:
        continue
        
    if m[0] == 'H':
        r1,r2 = env.rate_1vs1(r1,r2)
        tr1, tr2 = env2.rate([tr1,tr2], [0,1])
    elif m[0] == 'D':
        r1,r2 = env.rate_1vs1(r1,r2,drawn=True)
        tr1, tr2 = env2.rate([tr1,tr2], [0,0])
    elif m[0] =='A':
        r2,r1 = env.rate_1vs1(r2,r1)
        tr2, tr1 = env2.rate([tr2,tr1], [0,1])

    else:
        print('wrong result: '+m[0])
    
    ix = np.argmax(probs)
    stuff.append(np.subtract(probs,oh[m[0]])**2)
    conf_matrix[ix] = np.add(conf_matrix[ix], oh[m[0]])
    pred = np.add(pred, np.multiply(oh[m[0]], onehot[ix]))
    
    teams[t1] = r1
    teams[t2] = r2
    dates[t1] = date_new
    dates[t2] = date_new
    
    for i,pr in enumerate(tr1+tr2):
        players[int(m[i+4]/1000000)] = pr
    
    
print('%.2f $ from %s bets' % (budget,bets))
print(np.mean(stuff, axis = 0))
print('correct: ', pred, ', insgesamt %d/%d (%.3f)' % (sum(pred), len(stuff), sum(pred)/len(stuff)))
for l in conf_matrix:
    print(' %5d | %5d | %5d ' % (l[0], l[1], l[2]))

100.00 $ from 0 bets
[ 0.24187448  0.1931603   0.19817969]
correct:  [11445     0  3016] , insgesamt 14461/30365 (0.476)
 11445 |  6082 |  5817 
     0 |     0 |     0 
  2152 |  1853 |  3016 
